services:
  _defaults:
    public: true

  cdigruttola.paypaltracking.core.domain.command_handler.add_paypal_carrier_tracking_handler:
    class: cdigruttola\PaypalTracking\Core\Domain\PayPalCarrierTracking\CommandHandler\AddPayPalCarrierTrackingHandler
    tags:
      - name: tactician.handler
        command: 'cdigruttola\PaypalTracking\Core\Domain\PayPalCarrierTracking\Command\AddPayPalCarrierTrackingCommand'

  cdigruttola.paypaltracking.core.domain.query_handler.get_paypal_carrier_tracking_for_editing:
    class: cdigruttola\PaypalTracking\Core\Domain\PayPalCarrierTracking\QueryHandler\GetPayPalCarrierTrackingForEditingHandler
    tags:
      - name: tactician.handler
        command: cdigruttola\PaypalTracking\Core\Domain\PayPalCarrierTracking\Query\GetPayPalCarrierTrackingForEditing

  cdigruttola.paypaltracking.core.domain.command_handler.edit_paypal_carrier_tracking_handler:
    class: cdigruttola\PaypalTracking\Core\Domain\PayPalCarrierTracking\CommandHandler\EditPayPalCarrierTrackingHandler
    tags:
      - name: tactician.handler
        command: cdigruttola\PaypalTracking\Core\Domain\PayPalCarrierTracking\Command\EditPayPalCarrierTrackingCommand

  cdigruttola.paypaltracking.core.domain.command_handler.toggle_worldwide_paypal_carrier_tracking_handler:
    class: cdigruttola\PaypalTracking\Core\Domain\PayPalCarrierTracking\CommandHandler\ToggleWorldwidePayPalCarrierTrackingHandler
    tags:
      - name: tactician.handler
        command: cdigruttola\PaypalTracking\Core\Domain\PayPalCarrierTracking\Command\ToggleWorldwidePayPalCarrierTrackingCommand
