imports:
  - { resource: hooks.yml }

services:
  _defaults:
    public: true

  cdigruttola.paypaltracking.module:
    class: Paypaltracking
    factory: [ 'Module', 'getInstanceByName' ]
    public: false
    arguments:
      - 'paypaltracking'

  cdigruttola.paypal.tracking.client:
    class: cdigruttola\PaypalTracking\Admin\Api\Tracking\TrackingClient
    arguments:
      - '@cdigruttola.paypaltracking.repository.carrier'

  cdigruttola.paypaltracking.repository.order:
    class: cdigruttola\PaypalTracking\Repository\OrderRepository
    public: true

  cdigruttola.paypaltracking.service.paypal_carrier_tracking:
    class: cdigruttola\PaypalTracking\Service\Admin\AdminPayPalTrackingService
    arguments:
      - '@cdigruttola.paypaltracking.repository.order'
      - '@cdigruttola.paypaltracking.repository.carrier'
      - '@cdigruttola.paypal.tracking.client'
    public: true

  cdigruttola.paypaltracking.repository.carrier:
    class: cdigruttola\PaypalTracking\Repository\PaypalCarrierTrackingRepository
    public: true
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - cdigruttola\PaypalTracking\Entity\PaypalCarrierTracking
