services:
  _defaults:
    public: true

  cdigruttola.paypaltracking.module:
    class: Paypaltracking
    factory: [ 'Module', 'getInstanceByName' ]
    public: false
    arguments:
      - 'paypaltracking'

  cdigruttola.paypaltracking.repository.order:
    class: cdigruttola\PaypalTracking\Repository\OrderRepository
    public: true

  cdigruttola.paypaltracking.repository.carrier:
    class: cdigruttola\PaypalTracking\Repository\PaypalCarrierTrackingRepository
    public: true
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - cdigruttola\PaypalTracking\Entity\PaypalCarrierTracking
