<?php
/**
 * Copyright since 2007 Carmine Di Gruttola
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to http://www.prestashop.com for more information.
 *
 * @author    cdigruttola <c.digruttola@hotmail.it>
 * @copyright Copyright since 2007 Carmine Di Gruttola
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

namespace cdigruttola\Module\PaypalTracking\Form\Admin;

use PrestaShopBundle\Form\Admin\Type\CountryChoiceType;
use PrestaShopBundle\Form\Admin\Type\SwitchType;
use PrestaShopBundle\Form\Admin\Type\TranslatorAwareType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Translation\TranslatorInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

if (!defined('_PS_VERSION_')) {
    exit;
}

class PayPalCarrierTrackingType extends TranslatorAwareType
{
    public const PAYPAL_CARRIERS = [
        'VNM' => [
            'Vietnam Post' => 'VNM_VIETNAM_POST',
            'ViettelPost' => 'VNM_VIETTELPOST',
            'Nhat Tin Logistics' => 'NTLOGISTICS_VN',
            'Kerry Express (Vietnam) Co Ltd' => 'KERRYTTC_VN',
            'J&T Express Vietnam' => 'JTEXPRESS_VN',
        ],
        'URY' => [
            'Correo Uruguayo' => 'CORREO_UY',
        ],
        'ARE' => [
            'SKYNET UAE' => 'SKYNET_UAE',
            'One click delivery services' => 'ONECLICK',
            'Mena 360 (Fetchr' => 'FETCHR_WEBHOOK',
            'Mara Xpress' => 'MARA_XPRESS',
            'Beone Logistics' => 'IBEONE',
        ],
        'UKR' => [
            'UkrPoshta' => 'POSTA_UKR',
            'Nova Poshta (novaposhta.ua' => 'NOVA_POSHTA',
            'Nova Poshta (International' => 'NOVA_POSHTA_INT',
        ],
        'CHE' => [
            'ViaEurope' => 'VIAEUROPE',
            'Swiss Post FTP' => 'SWISS_POST_FTP',
            'Planzer Group' => 'PLANZER',
            'Asendia HonKong' => 'ASENDIA_HK',
        ],
        'ZAF' => [
            'Specialised Freight' => 'ZA_SPECIALISED_FREIGHT',
            'RAM courier' => 'RAM',
            'MDS Collivery Pty (Ltd' => 'COLLIVERY',
            'Internet Express' => 'INTEXPRESS',
            'The Courier Guy' => 'THECOURIERGUY',
            'South African Post Office' => 'SOUTH_AFRICAN_POST_OFFICE',
            'Skynet World Wide Express South Africa' => 'SKYNET_ZA',
            'Courier IT' => 'ZA_COURIERIT',
            'Dawn Wing' => 'DAWN_WING',
            'DPE South Africa' => 'DPE_SOUTH_AFRC',
        ],
        'THA' => [
            'Thailand Post (www.thailandpost.co.th' => 'THA_THAILAND_POST',
            'SKYBOX' => 'SKYBOX',
            'Ninja van Thai' => 'NINJAVAN_THAI',
            'Nim Express' => 'NIM_EXPRESS',
            'Sendit' => 'SENDIT',
            'Fastrak Services' => 'FASTRK_SERV',
            'Dynamic Logistics' => 'THA_DYNAMIC_LOGISTICS',
            'Flash Express' => 'FLASHEXPRESS',
            'CJ Korea Express' => 'CJ_KR',
            'Alphafast (www.alphafast.com' => 'ALPHAFAST',
        ],
        'SVN' => [
            'Post of Slovenia' => 'POST_SLOVENIA',
            'GLS Slovenia' => 'GLS_SLOVEN',
        ],
        'SVK' => [
            'GLS General Logistics Systems Slovakia s.r.o' => 'GLS_SLOV',
        ],
        'ESP' => [
            'Viaxpress' => 'VIA_EXPRESS',
            'tourline' => 'TOURLINE',
            'TNT global' => 'GLOBAL_TNT',
            'TNT Express' => 'TNT',
            'SZENDEX' => 'SZENDEX',
            'Spanish Seur API' => 'SEUR_SP_API',
            'Spring GDS' => 'SPRING_GDS',
            'Seur Spain' => 'SEUR_ES',
            'NACEX' => 'NACEX',
            'SEUR portugal' => 'PRT_SEUR',
            'TIPSA courier' => 'TIPSA',
            'SEUR International' => 'PRT_INT_SEUR',
            'Zeleris' => 'ZELERIS',
            'Paack courier' => 'PAACK_WEBHOOK',
            'CBL Logistica' => 'CBL_LOGISTICA',
            'Packlink' => 'ESP_PACKLINK',
            'THT Netherland' => 'TNT_NL',
            'Redur Spain' => 'ESP_REDUR',
            'NACEX Spain' => 'ESP_NACEX',
            'MRW spain' => 'ESP_MRW',
            'Envialia Reference' => 'ENVIALIA_REFERENCE',
            'MRW courier' => 'MRW_FTP',
            'Integra2' => 'INTEGRA2_FTP',
            'Envialia' => 'ESP_ENVIALIA',
            'ASIGNA courier' => 'ASIGNA',
            'DHL parcel Spain(www.dhl.com' => 'DHL_PARCEL_ES',
            'VAMOX' => 'VAMOX',
            'Correos Express' => 'CORREOS_EXPRESS',
            'DHL Spain(www.dhl.com' => 'DHL_ES',
            'AB Custom Group' => 'ABCUSTOM',
            'ASM(GLS Spain' => 'ESP_ASM',
            'ECOSCOOTING' => 'ECOSCOOTING',
            'Ader couriers' => 'ADERONLINE',
        ],
        'SRB' => [
            'Posta Serbia' => 'POST_SERBIA',
        ],
        'SAU' => [
            'Thabit Logistics' => 'THABIT_LOGISTICS',
            'Zajil Express Company' => 'ZAJIL_EXPRESS',
            'SMSA Express' => 'SMSA_EXPRESS',
            'Saudi Post' => 'SAU_SAUDI_POST',
        ],
        'RUS' => [
            'Pony express' => 'PONY_EXPRESS',
            'GBS-Broker' => 'GBS_BROKER',
            'DobroPost' => 'DOBROPOST',
            'DHL Parcel Russia' => 'DHL_PARCEL_RU',
            'CSE courier' => 'CSE',
            'ShopfansRU LLC' => 'SHOPFANS',
            'DPD Russia' => 'DPD_RU',
            'Expresssale' => 'EXPRESSSALE',
            'Boxberry courier' => 'BOX_BERRY',
        ],
        'ROU' => [
            'Post Roman (www.posta-romana.ro' => 'POSTA_RO',
            'DPD Romania' => 'DPD_RO',
        ],
        'SWE' => [
            'DB Schenker Sweden' => 'DBSCHENKER_SV',
            'Bring' => 'BRING',
            'DB Schenker (www.dbschenker.com' => 'DBSCHENKER_SE',
            'Airmee couriers' => 'AIRMEE_WEBHOOK',
        ],
        'PRT' => [
            'CTT Portugal' => 'PRT_CTT',
            'Chronopost Portugal' => 'PRT_CHRONOPOST',
            'Carriers courier' => 'CARRIERS',
            'Delnext' => 'DELNEXT',
            'Bneed courier' => 'BNEED',
            'Adicional Logistics' => 'ADICIONAL',
        ],
        'PHL' => [
            'Xpost.ph' => 'XPOST',
            'Ximex Delivery Express' => 'XDE_WEBHOOK',
            'RAF Philippines' => 'RAF_PH',
            'PIXSELL LOGISTICS' => 'PIXSELL',
            'Jam Express Philippines' => 'PHL_JAMEXPRESS',
            '2GO Courier' => 'TWO_GO',
        ],
        'NZL' => [
            'Toll New Zealand' => 'TOLL_NZ',
            'Mainfreight' => 'MAINFREIGHT',
            'Interparcel New Zealand' => 'INTERPARCEL_NZ',
            'New Zealand Post' => 'NZ_NZ_POST',
            'Fastway New Zealand' => 'FASTWAY_NZ',
        ],
        'MEX' => [
            'Paquetexpress' => 'PAQUETEXPRESS',
            'Hound Express' => 'HOUNDEXPRESS',
            'Redpack' => 'MEX_REDPACK',
            'Grupo ampm' => 'GRUPO',
            'Estafeta (www.estafeta.com' => 'MEX_ESTAFETA',
            'Ivoy courier' => 'IVOY_WEBHOOK',
            'mexico senda express' => 'MEX_SENDA',
            'correos mexico' => 'CORREOS_DE_MEXICO',
        ],
        'GBR' => [
            'Yodel (www.yodel.co.uk' => 'UK_YODEL',
            'XDP Express' => 'UK_XDP',
            'Whistl' => 'WHISTL',
            'UK mail (ukmail.com' => 'UK_UK_MAIL',
            'Tuffnells Parcels Express' => 'GB_TUFFNELLS',
            'TNT UK Reference' => 'TNT_UK_REFR',
            'TNT UK Limited (www.tnt.com' => 'TNT_UK',
            'APG eCommerce Solutions' => 'APG',
            'TDG – The Delivery Group' => 'THEDELIVERYGROUP',
            'The Pallet Network' => 'PALLET_NETWORK',
            'Swiship UK' => 'AMAZON_FBA_SWISHIP',
            'FedEx® UK' => 'FEDEX_UK',
            'Parcelink Logistics' => 'PARCELINKLOGISTICS',
            'Tuffnells Parcels Express- Reference' => 'TUFFNELLS_REFERENCE',
            'Panther Reference' => 'PANTHER_REFERENCE',
            'Caribou' => 'CARIBOU',
            'OCS WORLDWIDE' => 'OCS_WORLDWIDE',
            'Norsk Global' => 'GB_NORSK',
            'MyHermes UK' => 'MYHERMES',
            'Home Delivery Solutions Ltd' => 'HOME_DELIVERY_SOLUTIONS',
            'dhl UK' => 'DHL_UK',
            'ARK Logistics' => 'ARK_LOGISTICS',
            'GBA Services Ltd' => 'GBA',
            'Furdeco' => 'FURDECO',
            'DX (SFTP' => 'DX_SFTP',
            'Xpert Delivery' => 'XPERT_DELIVERY',
            'wnDirect' => 'WNDIRECT',
            'DMSMatrix' => 'DMS_MATRIX',
            'XDP Express Reference' => 'XDP_UK_REFERENCE',
            'Plus UK Logistics' => 'PLUS_LOG_UK',
            'EU Fleet Solutions' => 'EU_FLEET_SOLUTIONS',
            'Direct Parcels' => 'DIRECTPARCELS',
            'Diamond Eurogistics Limited' => 'DIAMOND_EUROGISTICS',
            'B&H Worldwide' => 'BH_WORLDWIDE',
            'Interparcel UK' => 'INTERPARCEL_UK',
            'DAI Post' => 'DAIGLOBALTRACK',
            'Deltec Courier' => 'DELTEC_UK',
            'National Sameday' => 'NATIONAL_SAMEDAY',
            'Bluecare Express Ltd' => 'BLUECARE',
            'Asendia UK' => 'ASENDIA_UK',
            'DPD Local' => 'DPD_LOCAL',
            'Arrow XL' => 'GB_ARROW',
            'RPD2man Deliveries' => 'RPD2MAN',
            'BirdSystem' => 'BIRDSYSTEM',
            'HermesWorld UK' => 'HERMES',
            'DHl (Reference number' => 'DHL_REFR',
            'Amazon Shipping' => 'AMAZON',
            'AO Logistics' => 'AO_COURIER',
            'Palletways' => 'PALLETWAYS',
            'DPD Local reference' => 'DPD_LOCAL_REF',
            'APC Overnight Consignment' => 'APC_OVERNIGHT_CONNUM',
            'Skynet UK' => 'SKYNET_UK',
            'Parcel2Go' => 'PARCEL2GO',
            'CAE Delivers' => 'CAE_DELIVERS',
            'Panther' => 'GB_PANTHER',
            'APC overnight (apc-overnight.com' => 'APC_OVERNIGHT',
            'GEM Worldwide' => 'GEMWORLDWIDE',
        ],
        'CAN' => [
            'Stallion Express' => 'STALLIONEXPRESS',
            'Routific' => 'ROUTIFIC_WEBHOOK',
            'Rivo (Air canada' => 'AIR_CANADA_GLOBAL',
            'Loomis Express' => 'LOOMIS_EXPRESS',
            'Nationex courier' => 'NATIONEX',
            'Ziing Final Mile Inc' => 'ZIINGFINALMILE',
            'MBW Courier Inc' => 'MBW',
            'Locus courier' => 'LOCUS_WEBHOOK',
            'GLS Logistic Systems Canada Ltd./Dicom' => 'DICOM',
            'Courant Plus' => 'COURANT_PLUS',
            'RPX Logistics' => 'RPXLOGISTICS',
            'ParcelPal' => 'PARCELPAL_WEBHOOK',
            'Corporate Couriers' => 'CORPORATECOURIERS_WEBHOOK',
            'Estes Express Lines' => 'GLOBAL_ESTES',
            'Chit Chats' => 'CHITCHATS',
            'Canada Post' => 'CA_CANADA_POST',
        ],
        'MYS' => [
            'Wyngs' => 'WYNGS',
            'WePost Sdn Bhd' => 'WEPOST',
            'TAQBIN Malaysia' => 'TAQBIN_MY',
            'Skynet Malaysia' => 'MYS_SKYNET',
            'PICK UPP' => 'PICKUPP_MYS',
            'Nationwide Express Courier Services Bhd (www.nationwide.com.my' => 'NATIONWIDE_MY',
            'Mypostonline' => 'MYS_MYPOST_ONLINE',
            'M Xpress Sdn Bhd' => 'M_XPRESS',
            'Logistika' => 'LOGISTIKA',
            'Line Clear Express & Logistics Sdn Bhd' => 'LINE',
            'ABX Express' => 'ABXEXPRESS_MY',
            'City-Link Express' => 'CITYLINK_MY',
            'Jocom' => 'JOCOM',
            'Malaysia Post' => 'MYS_MYS_POST',
            'CJ International malaysia' => 'CJ_INT_MY',
            'JINSUNG TRADING' => 'JINSUNG',
            'CJ Century' => 'CJ_CENTURY',
            'Airpak Express' => 'MYS_AIRPAK',
            'GDEX courier' => 'MYS_GDEX',
            'J&T EXPRESS MALAYSIA' => 'JTEXPRESS',
            'FMX' => 'FMX',
            'ninja van (www.ninjavan.co' => 'NINJAVAN_MY',
            'CollectCo' => 'COLLECTCO',
            'ZeptoExpress' => 'ZEPTO_EXPRESS',
            'Matdespatch' => 'MATDESPATCH',
            'Kangaroo Worldwide Express' => 'KANGAROO_MY',
        ],
        'BGD' => [
            'Paperfly Private Limited' => 'PAPERFLY',
        ],
        'LTU' => [
            'Venipak' => 'VENIPAK',
        ],
        'NGA' => [
            'NIpost (www.nipost.gov.ng' => 'NIPOST_NG',
        ],
        'LVA' => [
            'Latvijas Pasts' => 'LATVIJAS_PASTS',
            'CDEK courier' => 'CDEK',
        ],
        'TUR' => [
            'Yurtici Kargo' => 'YURTICI_KARGO',
            'ShipEntegra' => 'SHIPENTEGRA',
            'PTT Post' => 'PTT_POST',
            'CDEK TR' => 'CDEK_TR',
            'PTS courier' => 'PTS',
            'ASE KARGO' => 'ASE',
        ],
        'DNK' => [
            'Xpressen courier' => 'XPRESSEN_DK',
            'PostNord Logistics' => 'POSTNORD_LOGISTICS',
            'Danske Fragtaend' => 'DANSKE_FRAGT',
            'ostnord denmark' => 'POSTNORD_LOGISTICS_DK',
            'Budbee courier' => 'BUDBEE_WEBHOOK',
        ],
        'CHN' => [
            'yingnuo logistics' => 'YINGNUO_LOGISTICS',
            'Yanwen Logistics' => 'YANWEN',
            'WishPost' => 'CN_WISHPOST',
            'WeDo Logistics' => 'CN_WEDO',
            'VIWO IoT' => 'VIWO',
            'YDH express' => 'YDH_EXPRESS',
            'TONDA GLOBAL' => 'TARRIVE',
            'Sunyou Post' => 'SYPOST',
            'Shanghai Aqrum Chemical Logistics Co.Ltd' => 'DAJIN',
            'SFC Service' => 'SFCSERVICE',
            'SF International' => 'SFB2C',
            'SF Express (www.sf-express.com' => 'CN_SF_EXPRESS',
            'Ruston' => 'RUSTON',
            'PFC Express' => 'PFCEXPRESS',
            'PayPal Package' => 'CN_PAYPAL_PACKAGE',
            'Pan-Asia International' => 'PAN_ASIA',
            'Pago Logistics' => 'PAGO',
            'Tophatter Express' => 'TOPHATTEREXPRESS',
            'padtf.com' => 'PADTF',
            'Nanjing Woyuan' => 'NANJINGWOYUAN',
            'Morelink' => 'MORE_LINK',
            'Sinotrans' => 'SINOTRANS',
            'LTL COURIER' => 'LTL',
            'lightning monkey' => 'SDH_SCM',
            'Joom Logistics' => 'JOOM_LOGIS',
            'Wise Express' => 'WISE_EXPRESS',
            'jindouyun courier' => 'JINDOUYUN',
            'YTO Express' => 'YTO',
            'J-Net' => 'J_NET',
            'STONE3PL' => 'STONE3PL',
            'Intel-Valley Supply chain (ShenZhen) Co. Ltd' => 'INTEL_VALLEY',
            'YunExpress' => 'YUNEXPRESS',
            'Logisters' => 'LOGISTERS',
            'K1 Express' => 'K1_EXPRESS',
            'GANGBAO Supplychain' => 'GANGBAO',
            'IDEX courier' => 'IDEXPRESS',
            'One World Express' => 'ONEWORLDEXPRESS',
            'Haidaibao' => 'HDB',
            'ANSERX courier' => 'ANSERX',
            'Equick China' => 'CN_EQUICK',
            'Fulfillme' => 'FULFILLME',
            'Eshun international Logistic' => 'ZES_EXPRESS',
            'DTD Express' => 'DTD_EXPR',
            'Joying Box' => 'JOYING_BOX',
            'Post56' => 'CN_POST56',
            'EMPS Express' => 'EMPS_CN',
            'FAR international' => 'FAR_INTERNATIONAL',
            'DPE Express' => 'DPE_EXPRESS',
            'RETS express' => 'ETS_EXPRESS',
            'leader' => 'LEADER',
            'DIDADI Logistics tech' => 'DIDADI',
            'ZJS International' => 'ZJS_EXPRESS',
            'WanbExpress' => 'WANBEXPRESS',
            'Lalamove' => 'LALAMOVE',
            'HX Express' => 'HX_EXPRESS',
            'DEX-I courier' => 'DEX_I',
            'GoFly' => 'CN_GOFLY',
            'HUAHANG EXPRESS' => 'HUAHAN_EXPRESS',
            'Kua Yue Express' => 'KY_EXPRESS',
            'Cpacket couriers' => 'CPACKET',
            '17 Post Service' => 'CN_17POST',
            'CometTech' => 'COMET_TECH',
            'Qingdao HKD International Logistics' => 'HKD',
            'ACS Worldwide Express' => 'ACSWORLDWIDE',
            'CNE Express' => 'CNEXPS',
            'Yunda Express' => 'CN_YUNDA',
            'CND Express' => 'CNDEXPRESS',
            'MXE Express' => 'MXE',
            'AuPost China' => 'AUPOST_CN',
            'CJ Packet' => 'CJPACKET',
            'XQ Express' => 'XQ_EXPRESS',
            'Weaship' => 'WEASHIP',
            'Hua Han Logistics' => 'HH_EXP',
            'WinIt' => 'WINIT',
            'Chukou1' => 'CHUKOU1',
            'Cuckoo Express' => 'CUCKOOEXPRESS',
            'China Post' => 'CN_CHINA_POST_EMS',
            'TopYou' => 'TOPYOU',
            'GESWL Express' => 'GESWL',
            'FarGood' => 'FARGOOD',
            'buylogic' => 'BUYLOGIC',
            'Yilian (Elian) Supply Chain' => 'ELIAN_POST',
            'Huodull' => 'HUODULL',
            'ZTO Express' => 'ZTO_EXPRESS',
            'ucexpress' => 'UC_EXPRE',
            'AliExpress Standard Shipping' => 'CAINIAO',
            'BoxC courier' => 'CN_BOXC',
            'CGS Express' => 'CGS_EXPRESS',
            'Captain Express International' => 'CPEX',
            'Haidaibao (BOX' => 'HDB_BOX',
            'Best Express' => 'CN_BESTEXPRESS',
            'LTIAN EXP' => 'LTIANEXP',
            'Anjun couriers' => 'ANJUN',
            'BEL North Russia' => 'BEL_RS',
            'Eshipping' => 'ESHIPPING',
            'SFC' => 'SFC_LOGISTICS',
            'Clevy Links' => 'CLEVY_LINKS',
        ],
        'JEY' => [
            'Jersey Post' => 'JERSEY_POST',
        ],
        'NOR' => [
            'Helthjem' => 'HELTHJEM',
        ],
        'HRV' => [
            'Overseas Express' => 'OVERSE_EXP',
            'Hrvatska posta' => 'HRV_HRVATSKA',
            'GLS Croatia' => 'GLS_CROTIA',
        ],
        'LAO' => [
            'Lao Post' => 'LAO_POST',
        ],
        'ITA' => [
            'TNT-Click Italy' => 'TNT_CLICK_IT',
            'Nexive (TNT Post Italy' => 'IT_NEXIVE',
            'HR Parcel' => 'HRPARCEL',
            'Milkman courier' => 'MILKMAN',
            'SAILPOST' => 'SAILPOST',
            'DMM Network' => 'DMM_NETWORK',
            'BRT Bartolini(Sender Reference' => 'BRT_IT_SENDER_REF',
            'Blink' => 'BLINKLASTMILE',
            'GLS Italy' => 'GLS_ITALY',
            'Arco Spedizioni SP' => 'ARCO_SPEDIZIONI',
            'LICCARDI EXPRESS COURIER' => 'LICCARDI_EXPRESS',
            'Poste italiane (www.poste.it' => 'IT_POSTE_ITALIA',
            'BRT couriers Italy (www.brt.it' => 'BRT_IT',
            'SDA Italy' => 'SDA_IT',
            'i-dika' => 'I_DIKA',
            'BRT Bartolini(Parcel ID' => 'BRT_IT_PARCELID',
        ],
        'IND' => [
            'Shree Maruti Courier Services Pvt Ltd' => 'SHREE_MARUTI',
            'Shree Anjani Courier' => 'SHREE_ANJANI_COURIER',
            'SHREE NANDAN COURIER' => 'SHREENANDANCOURIER',
            'Safexpress' => 'IND_SAFEEXPRESS',
            'Pickrr' => 'PICKRR',
            'Parcelled.in' => 'PARCELLED_IN',
            'SHREE TIRUPATI COURIER SERVICES PVT. LTD' => 'SHREETIRUPATI',
            'OCS ANA Group' => 'OCS',
            'First Flight Couriers' => 'IND_FIRSTFLIGHT',
            'GoJavas' => 'IND_GOJAVAS',
            'Scudex Express' => 'SCUDEX_EXPRESS',
            'Ecom Express' => 'IND_ECOM',
            'Ekart logistics (ekartlogistics.com' => 'EKART',
            'LexShip' => 'LEXSHIP',
            'Bombino Express Pvt' => 'BOMBINOEXP',
            'DTDC India' => 'DTDC_IN',
            'Delhivery India' => 'IND_DELHIVERY',
            'SPOTON Logistics Pvt Ltd' => 'SPOTON',
            'Holisol' => 'HOLISOL',
            'Gati-KWE' => 'IND_GATI',
            'Trackon Couriers Pvt. Ltd' => 'TRACKON',
            'DELIVERYONTIME LOGISTICS PVT LTD' => 'DELIVERYONTIME',
        ],
        'ISR' => [
            'Israel Post Domestic' => 'ISR_POST_DOMESTIC',
            'Israel Post' => 'ISRAEL_POST',
        ],
        'TWN' => [
            'Tai Wan Global Business' => 'GLOBAL_EXPRESS',
            'Kerry TJ Logistics' => 'KERRYTJ',
            'HCT LOGISTICS CO.LTD' => 'HCT_LOGISTICS',
            'CTC Express' => 'CTC_EXPRESS',
            'Dimerco Express Group' => 'DIMERCO',
            'PRESIDENT TRANSNET CORP' => 'PRESIDENT_TRANS',
            'cnwangtong' => 'CNWANGTONG',
        ],
        'IDN' => [
            'Wahana express (www.wahana.com' => 'WAHANA_ID',
            'Trans Kargo Internasional' => 'TRANS_KARGO',
            'SAP EXPRESS' => 'SAP_EXPRESS',
            'Red Carpet Logistics' => 'RCL',
            'Sin Global Express' => 'SIN_GLBL',
            'PT Prima Multi Cipta' => 'PRIMAMULTICIPTA',
            'Ninjavan Webhook' => 'NINJAVAN_WB',
            'KURASI' => 'KURASI',
            'Ninja Van Indonesia' => 'NINJAVAN_ID',
            'AlfaTrex' => 'ALFATREX',
            'PT MGLOBAL LOGISTICS INDONESIA' => 'MGLOBAL',
            'JX courier' => 'JX',
            'Tiki shipment' => 'TIKI_ID',
            'INDOPAKET' => 'INDOPAKET',
            'RPX Indonesia' => 'RPX_ID',
            'Choir Express Indonesia' => 'CHOIR_EXP',
        ],
        'PAK' => [
            'TCS courier' => 'TCS',
            'forrun Pvt Ltd (Arpatech Venture' => 'FORRUN',
        ],
        'BIH' => [
            'BH Posta (www.posta.ba' => 'BH_POSTA',
        ],
        'FIN' => [
            'Posti courier' => 'POSTI',
            'Matkahuolto' => 'MATKAHUOLTO',
        ],
        'POL' => [
            'Royal Mail' => 'ROYAL_MAIL',
            'Poczta Polska (www.poczta-polska.pl' => 'PL_POCZTA_POLSKA',
            'FedEx® Poland Domestic' => 'FEDEX_POLAND',
            'InPost Paczkomaty' => 'INPOST_PACZKOMATY',
            'DPD Poland' => 'DPD_POLAND',
            'DHL Poland' => 'DHL_PL',
        ],
        'GRC' => [
            'Speed Couriers' => 'SPEEDCOURIERS_GR',
            'SPEEDEX couriers' => 'SPEEDEXCOURIER',
            'Geniki Taxydromiki' => 'GENIKI_GR',
            'Easy Mail' => 'EASY_MAIL',
            'ACS Courier' => 'ACS_GR',
        ],
        'EST' => [
            'Omniva' => 'OMNIVA',
        ],
        'KOR' => [
            'Tolos courier' => 'TOLOS',
            'SRE Korea (www.srekorea.co.kr' => 'SRE_KOREA',
            'Lotte Global Logistics' => 'LOTTE',
            'ShipGate' => 'SHIP_GATE',
            'Kyungdong Parcel' => 'KYUNGDONG_PARCEL',
            'Rincos' => 'RINCOS',
            'Koreapost (www.koreapost.go.kr' => 'KR_KOREA_POST',
            'SHIPTER' => 'SHIPTER',
            'Korea Post' => 'KPOST',
            'Croshot' => 'CROSHOT',
            'eParcel Korea' => 'EPARCEL_KR',
            'Rocket Parcel International' => 'ROCKET_PARCEL',
            'Doora Logistics' => 'DOORA',
            'Cello Square' => 'CELLO_SQUARE',
        ],
        'CZE' => [
            'GLS Czech Republic' => 'GLS_CZ',
            'Czech Post' => 'CESKA_CZ',
        ],
        'CYP' => [
            'cyprus post' => 'CYPRUS_POST_CYP',
        ],
        'USA' => [
            'YRC courier' => 'US_YRC',
            'XPO logistics' => 'XPO_LOGISTICS',
            'Westgate Global' => 'WESTGATE_GL',
            'West Bank Courier' => 'WESTBANK_COURIER',
            'USF Reddaway' => 'USF_REDDAWAY',
            'UPS Mail Innovations' => 'UPS_MAIL_INNOVATIONS',
            'TRUMPCARD LLC' => 'TRUMPCARD',
            'Transgroup courier' => 'LOGISTYX_TRANSGROUP',
            'TForce Final Mile' => 'TFORCE_FINALMILE',
            'United States Postal Service' => 'USPS',
            'Tazmanian Freight Systems' => 'TAZMANIAN_FREIGHT',
            'Yakit courier' => 'YAKIT',
            'Sonic Transportation & Logistics' => 'SONICTL',
            'Shiptor' => 'SHIPTOR',
            'A Duie Pyle' => 'ADUIEPYLE',
            'Pitney Bowes' => 'PITNEY_BOWES',
            'OSM Worldwide' => 'OSM_WORLDWIDE',
            'Old Dominion Freight Line' => 'US_OLD_DOMINION',
            'MailAmericas' => 'MAILAMERICAS',
            'LaserShip' => 'US_LASERSHIP',
            'Innovel courier' => 'DESCARTES',
            'Zinc courier' => 'ZINC',
            'Newegg Express' => 'NEWEGGEXPRESS',
            'Spee-Dee Delivery' => 'SPEEDEE',
            'RL Carriers' => 'RL_US',
            'Asendia USA' => 'ASENDIA_US',
            'GlobalTranz' => 'GLOBALTRANZ',
            'Wizmo' => 'WIZMO',
            'Pilot Freight Services' => 'PILOT_FREIGHT',
            'Amazon Shipping + Amazon MCF' => 'AMAZON_SHIP_MCF',
            'Agility' => 'AGILITY',
            'Gio Express' => 'GIO_EXPRESS',
            'FedEx International MailService' => 'FEDEX_INTL_MLSERV',
            'Hipshipper' => 'HIPSHIPPER',
            'Aprisa Express' => 'APRISAEXPRESS',
            'FedEx Cross Border' => 'FEDEX_CROSSBORDER',
            'FirstMile' => 'FIRSTMILE',
            'Fedex' => 'FEDEX',
            'ePost Global' => 'EPST_GLBL',
            'DoorDash' => 'DOORDASH_WEBHOOK',
            'Freightquote by C.H. Robinson' => 'FREIGHTQUOTE',
            'FDSEXPRESS' => 'FDSEXPRESS',
            'Destiny Transportation' => 'DESTINY',
            'EP-Box courier' => 'EP_BOX',
            'i-parcel' => 'GLOBAL_IPARCEL',
            'Dayton Freight' => 'DAYTON_FREIGHT',
            'Sutton Transport' => 'SUTTON',
            'DHL Supply Chain APAC' => 'DHL_SUPPLY_CHAIN',
            'Con-way Freight' => 'CON_WAY',
            'Champion Logistics' => 'CHAMPION_LOGISTICS',
            'Aeronet couriers' => 'AERONET',
            'Fulfilla' => 'FULFILLA',
            'Bond courier' => 'BOND',
            'APC postal logistics germany' => 'GB_APC',
            'uShip courier' => 'USHIP',
            'AAA Cooper' => 'AAA_COOPER',
            'Lone Star Overnight' => 'LONESTAR',
            'Saia LTL Freight' => 'SAIA_FREIGHT',
            'GSI EXPRESS' => 'GSI_EXPRESS',
            'ANICAM BOX EXPRESS' => 'ANICAM_BOX',
            'Qwintry Logistics' => 'QWINTRY',
            'PITT OHIO' => 'PITTOHIO',
            'Always Express' => 'ALWAYS_EXPRESS',
            'Southeastern Freight Lines' => 'SEFL',
            'PCF Final Mile' => 'PCFCORP',
            'Best Way Parcel' => 'BESTWAYPARCEL',
            'ABF Freight' => 'GLOBAL_ABF',
            'GSO(GLS-USA' => 'GSO',
            'Echo courier' => 'ECHO',
            'Amstan Logistics' => 'AMSTAN',
            'Aquiline' => 'AQUILINE',
        ],
        'BGR' => [
            'Bulgarian Posts' => 'BG_BULGARIAN_POST',
            'A1Post' => 'A1POST',
        ],
        'COL' => [
            'Coordinadora' => 'COORDINADORA',
        ],
        'DEU' => [
            'Raben Group' => 'RABEN_GROUP',
            'Streck Transport' => 'STRECK_TRANSPORT',
            'PARCEL ONE' => 'PARCELONE',
            'Swiship DE' => 'SWISHIP_DE',
            'liefery' => 'LIEFERY',
            'NOX NightTimeExpress' => 'NOX_NIGHT_TIME_EXPRESS',
            'Heppner Internationale Spedition GmbH & Co' => 'HEPPNER',
            'Go!Express and logistics' => 'GENERAL_OVERNIGHT',
            'Innight Express Germany GmbH (nox NachtExpress' => 'NOX_NACHTEXPRESS',
            'Gel Express Logistik' => 'GEL_EXPRESS',
            'Geis CZ' => 'GEIS',
            'Pressio' => 'PRESSIODE',
            'Hermes Einrichtungs Service GmbH & Co. KG' => 'HERMES_2MANN_HANDLING',
            'Hermes Germany' => 'HERMES_DE',
            'Fiege Logistics' => 'FIEGE',
            'AO Deutschland' => 'AO_DEUTSCHLAND',
            'DPD Germany' => 'DE_DPD_DELISTRACK',
        ],
        'HUN' => [
            'Magyar Post' => 'MAGYAR_HU',
            'DPD Hungary' => 'DPD_HGRY',
        ],
        'BRA' => [
            'Total Express' => 'TOTAL_EXPRESS',
            'Intelipost (TMS for LATAM' => 'INTELIPOST',
            'Frete Rapido' => 'FRETERAPIDO',
            'Directlog (www.directlog.com.br' => 'DIRECTLOG',
            'Correios Brazil' => 'BRA_CORREIOS',
        ],
        'IRL' => [
            'Wiseloads' => 'WISELOADS',
            'Fastway Ireland' => 'FASTWAY_IR',
            'DPD Ireland' => 'DPD_IR',
            'An Post' => 'AN_POST',
        ],
        'CHL' => [
            'STARKEN couriers' => 'STARKEN',
            'Blue Express' => 'BLUEX',
        ],
        'PRY' => [
            'AEX Group' => 'AEX',
        ],
        'AUS' => [
            'UBI Smart Parcel' => 'UBI_LOGISTICS',
            'Toll IPEC' => 'TOLL',
            'TIG Freight' => 'TIGFREIGHT',
            'TFM Xpress' => 'TFM',
            'XL Express' => 'XL_EXPRESS',
            'SortHub courier' => 'THENILE_WEBHOOK',
            'Shippit' => 'SHIPPIT',
            'Interparcel Australia' => 'INTERPARCEL_AU',
            'Australia Post' => 'AU_AU_POST',
            'DTDC Australia' => 'DTDC_AU',
            'DHL Supply Chain Australia' => 'DHL_AU',
            'Star Track Express' => 'STAR_TRACK_EXPRESS',
            'Sendle' => 'SENDLE',
            'Endeavour Delivery' => 'ENDEAVOUR_DELIVERY',
            'Direct Couriers' => 'DIRECTCOURIERS',
            'deliverE' => 'IND_DELIVREE',
            'PFL' => 'PFLOGISTICS',
            'Neway Transport' => 'NEWAY',
            'Border Express' => 'BORDEREXPRESS',
            'Parcelpoint' => 'PARCELPOINT',
            'ADSone' => 'ADSONE',
            'CouriersPlease (couriersplease.com.au' => 'COURIERS_PLEASE',
            'Cope Sensitive Freight' => 'COPE',
            'iCumulus' => 'ICUMULUS',
            'Designer Transport' => 'DESIGNERTRANSPORT_WEBHOOK',
            'Aramex Australia (formerly Fastway AU' => 'ARAMEX_AU',
            'Hunter Express' => 'HUNTER_EXPRESS',
            'StarTrack (startrack.com.au' => 'AUS_STARTRACK',
            'Allied Express' => 'ALLIEDEXPRESS',
            'Bonds Courier Service (bondscouriers.com.au' => 'BONDSCOURIERS',
            'Blue Star' => 'BLUESTAR',
        ],
        'GLOBAL' => [
            'Other' => 'OTHER',
            'Zuellig Pharma Korea' => 'ZUELLIGPHARMA_SFTP',
            'ZTO Express China' => 'ZTO_DOMESTIC',
            'yycom' => 'YYCOM',
            'Yodel International' => 'YODEL_INTNL',
            'Yodel Direct' => 'YODEL_DIR',
            'Yodel API' => 'YODEL_API',
            'YiFan Express' => 'YIFAN',
            'XPRESSBEES' => 'XPRESSBEES',
            'Xpedigo' => 'XPEDIGO',
            'WSP Express' => 'WSPEXPRESS',
            'Wineshipping' => 'WINESHIPPING_WEBHOOK',
            'Whistl' => 'WHISTL_SFTP',
            'WeShip' => 'WESHIP',
            'We World Express' => 'WEWORLDEXPRESS',
            'VOX SOLUCION EMPRESARIAL SRL' => 'VOX',
            'vnpost_ems' => 'VNPOST_EMS',
            'ViaXpress' => 'VIAXPRESS',
            'USPS Informed Visibility - Webhook' => 'USPS_WEBHOOK',
            'USPS API' => 'USPS_API',
            'Urgent Cargus' => 'URGENT_CARGUS',
            'UPS Freight' => 'UPS_FREIGHT',
            'UPS' => 'UPS_API',
            'up_express' => 'UP_EXPRESS',
            'United Parcel Service' => 'UPS',
            'United Delivery Service' => 'UDS',
            'UCS' => 'UCS',
            'YAMATO' => 'YAMATO',
            'Uber' => 'UBER_WEBHOOK',
            'Trusk France' => 'TRUSK',
            'Vir Transport' => 'VIRTRANSPORT_SFTP',
            'Trunkrs' => 'TRUNKRS',
            'Transport Ambientales' => 'TANET',
            'Trans2u' => 'TRANS2U',
            'Tourline Express' => 'TOURLINE_REFERENCE',
            'Top Ideal Express' => 'ESDEX',
            'Tonami' => 'TONAMI_FTP',
            'TOLL IPEC' => 'TOLL_IPEC',
            'Toll Group' => 'TOLL_WEBHOOK',
            'tnt_it' => 'TNT_IT',
            'TNT_ES' => 'TNT_ES',
            'TNT_CN' => 'TNT_CN',
            'tnt_au' => 'TNT_AU',
            'TNT Reference' => 'TNT_REFR',
            'TNT France Reference' => 'TNT_FR_REFERENCE',
            'Tipsa Reference' => 'TIPSA_REF',
            'Thijs Logistiek' => 'THIJS_NL',
            'The Custom Companies' => 'CUSTOMCO_API',
            'tecor' => 'TECOR',
            'TCS' => 'TCS_API',
            'Taiwan Post' => 'TW_TAIWAN_POST',
            'SWISS POST' => 'SWISS_POST',
            'Swiship' => 'SWISHIP',
            'startrack' => 'STARTRACK',
            'solistica' => 'SOLISTICA_API',
            'Snt Global Etrax' => 'SNTGLOBAL_API',
            'SMSA Express' => 'SMSA_EXPRESS_WEBHOOK',
            'SmartKargo' => 'SMARTKARGO',
            'Slovenska pošta' => 'SK_POSTA',
            'SkyPostal' => 'SKY_POSTAL',
            'SIODEMKA' => 'SIODEMKA',
            'Starlinks Global' => 'STARLINKS_API',
            'Sims Global' => 'SIMSGLOBAL',
            'SimpleTire' => 'SIMPLETIRE_WEBHOOK',
            'ShunBang Express' => 'SHUNBANG_EXPRESS',
            'ShipX' => 'SHIPX',
            'Shiprocket X' => 'SHIPROCKET',
            'Shippify, Inc' => 'SHIPPIFY',
            'Shippie' => 'SHIPPIE',
            'Sherpa' => 'SHERPA',
            'Shenzhen Jinghuada Logistics Co' => 'KWT',
            'shenzhen 1st International Logistics(Group)Co' => 'SHENZHEN',
            'SGT_IT' => 'SGT_IT',
            'SF Express China' => 'SF_EXPRESS_CN',
            'SF Express' => 'SF_EX',
            'Setel Express' => 'SETEL',
            'SerVIP' => 'SERVIP_WEBHOOK',
            'SEKO Worldwide' => 'SEKO_SFTP',
            'Seino' => 'SEINO_API',
            'Secretlab' => 'SECRETLAB_WEBHOOK',
            'Sber Logistics' => 'SBERLOGISTICS_RU',
            'Sagawa' => 'SAGAWA_API',
            'SAGAWA' => 'SAGAWA',
            'saee' => 'SAEE',
            'Russian post' => 'RUSSIAN_POST',
            'rrdonnelley' => 'RRDONNELLEY',
            'royalshipments' => 'ROYALSHIPMENTS',
            'Roche Internal Courier' => 'ROCHE_INTERNAL_SFTP',
            'T&W Delivery' => 'LOGINEXT_WEBHOOK',
            'Rivo' => 'AIR_CANADA',
            'Rhenus Logistics UK' => 'RHENUS_UK_API',
            'TNT_PL' => 'TNT_PL',
            'Relais Colis' => 'RELAISCOLIS',
            'SkyNet Worldwide Express' => 'SKYNET_WORLDWIDE',
            'Ransa' => 'RANSA_WEBHOOK',
            'Quiqup' => 'QUIQUP',
            'Quickstat Courier LLC' => 'QINTL_API',
            'QTrack' => 'QTRACK',
            'Purolator International' => 'PUROLATOR_INTERNATIONAL',
            'purolator' => 'PUROLATOR',
            'ProMed Delivery' => 'PROMEDDELIVERY',
            'Red je Pakketje' => 'REDJEPAKKETJE',
            'PROFESSIONAL COURIERS' => 'PROFESSIONAL_COURIERS',
            'Pro Carrier' => 'PROCARRIER',
            'PostPlus' => 'POSTPLUS',
            'Postnord sweden' => 'SWE_POSTNORD',
            'PostNL International' => 'POSTNL_INTERNATIONAL',
            'Xingyunyi Logistics' => 'XYY',
            'Product Care Services Limited' => 'PRODUCTCAREGROUP_SFTP',
            'Posten Norge (www.posten.no' => 'POSTEN_NORGE',
            'Post ONE' => 'POSTONE',
            'PolarSpeed Inc' => 'POLARSPEED',
            'Tomydoor' => 'TOMYDOOR',
            'Star Track Next Flight' => 'STAR_TRACK_NEXT_FLIGHT',
            'Pidge' => 'PIDGE',
            'TransVirtual' => 'TRANSVIRTUAL',
            'PHSE' => 'PHSE_API',
            'Pchome Express' => 'PCHOME_API',
            'Payo' => 'PAYO',
            'Parcelstars' => 'PARCELSTARS_WEBHOOK',
            'panther_order_number' => 'PANTHER_ORDER_NUMBER',
            'DPD Russia' => 'DPD_RU_API',
            'GAC' => 'GAC',
            'GDPharm Logistics' => 'GDPHARM',
            'Panther Reference' => 'PANTHER_REFERENCE_API',
            'Packs' => 'PACKS',
            'PACKFLEET' => 'PACKFLEET',
            'Omni Returns' => 'OMNIRPS_WEBHOOK',
            'Olive' => 'SHOPOLIVE',
            'T-cat' => 'T_CAT_API',
            'Fast & Furious' => 'FNF_ZA',
            'NYT SUPPLY CHAIN LOGISTICS Co., LTD' => 'NYTLOGISTICS',
            'NTL logistics' => 'NTL',
            'Better Trucks' => 'BETTERTRUCKS',
            'Malca Amit' => 'MALCA_AMIT_API',
            'Nova Poshta API' => 'NOVA_POSHTA_API',
            'Hellenic (Greece) Post' => 'HELLENIC_POST',
            'nightline_uk' => 'NIGHTLINE_UK',
            'Shopee Express' => 'SPX',
            'Newgistics' => 'NEWGISTICS',
            'Naeko Logistics' => 'NAEKO_FTP',
            'CRL Express' => 'CRLEXPRESS',
            'N&M Transfer Co., Inc' => 'NMTRANSFER',
            'TAQBIN Hong Kong' => 'TAQBIN_HK',
            'megasave' => 'MEGASAVE',
            'Pandago' => 'PANDAGO_API',
            'Averitt Express' => 'AVERITT',
            'mySendle' => 'MYSENDLE_API',
            'Naqel Express' => 'NAQEL_EXPRESS',
            'My DynaLogic' => 'MYDYNALOGIC',
            'Estes Forwarding Worldwide' => 'EFWNOW_API',
            'Movianto' => 'MOVIANTO',
            'Morning Global' => 'MORNINGLOBAL',
            'Pandion' => 'PANDION',
            'MONDIAL_BE' => 'MONDIAL_BE',
            'Worldnet Logistics' => 'WORLDNET',
            'CDL Last Mile' => 'CDLDELIVERS',
            'Mondial Relay Spain(Punto Pack' => 'MONDIALRELAY_ES',
            'MISUMI Group Inc' => 'MISUMI_CN',
            'Marken' => 'MARKEN',
            'Malca-Amit' => 'MALCA_AMIT',
            'Malaysia Post EMS / Pos Laju' => 'MYS_EMS',
            'Novofarma' => 'NOVOFARMA_WEBHOOK',
            'Etomars' => 'ETOMARS',
            'Mail Boxes Etc' => 'MAIL_BOX_ETC',
            'Toll Priority' => 'TOLL_PRIORITY',
            'maergo' => 'REIMAGINEDELIVERY',
            'Med Africa Logistics' => 'MEDAFRICA',
            'Helthjem' => 'HELTHJEM_API',
            'Home Logistics' => 'HOMELOGISTICS',
            'M3 Logistics' => 'M3LOGISTICS',
            'CORREOS DE ESPANA' => 'CORREOS_DE_ESPANA',
            'Logysto' => 'LOGYSTO',
            'Pgeon' => 'PGEON_API',
            'Value Logistics' => 'VALUE_WEBHOOK',
            'Moova' => 'MOOVA',
            'Logwin Logistics' => 'LOGWIN_LOGISTICS',
            'Loggi' => 'LOGGI',
            'Pakajo World' => 'PAKAJO',
            'LION PARCEL' => 'LION_PARCEL',
            'Lietuvos pastas' => 'LTU_LIETUVOS',
            'Shadowfax' => 'SHADOWFAX',
            'Lalamove' => 'LALAMOVE_API',
            'Kuehne + Nagel' => 'KUEHNE',
            'Meest' => 'MEEST',
            'PARCELFORCE' => 'PARCELFORCE',
            'Kerry Express TaiWan' => 'KERRY_EXPRESS_TW_API',
            'JNE Express (Jalur Nugraha Ekakurir' => 'IDN_JNE',
            'JCEX courier' => 'CN_JCEX',
            'GIO Express Ecourier' => 'GIO_ECOURIER_API',
            'KargomKolay (CargoMini' => 'KARGOMKOLAY',
            'J&T International logistics' => 'JT_LOGISTICS',
            'J&T CARGO' => 'JTCARGO',
            'Kerry Express Thailand' => 'THA_KERRY',
            'iThink Logistics' => 'ITHINKLOGISTICS',
            'TP Logistic' => 'THAIPARCELS',
            'INTERSMARTTRANS & SOLUTIONS SL' => 'INTERSMARTTRANS',
            'Kerry Logistics' => 'KERRY_EXPRESS_TH_WEBHOOK',
            'Inexpost' => 'INEXPOST',
            'Teliway SIC Express' => 'SIC_TELIWAY',
            'IMX' => 'IMX',
            'Rhenus Logistics' => 'RHENUS_GROUP',
            'Kerry Express Hong Kong' => 'HK_TGX',
            'iMile' => 'IMILE_API',
            'USPS Flats (Pitney Bowes' => 'PB_USPSFLATS_FTP',
            'FragilePAK' => 'FRAGILEPAK_SFTP',
            'elogistica' => 'ELOGISTICA',
            'imexglobalsolutions' => 'IMEXGLOBALSOLUTIONS',
            'Ilyang logistics' => 'ILYANGLOGIS',
            'idn_pos' => 'IDN_POS',
            'ICS COURIER' => 'ICSCOURIER',
            'HuanTong' => 'HUANTONG',
            'Mikropakket' => 'MIKROPAKKET',
            'HSDEXPRESS' => 'HSDEXPRESS',
            'Mothership' => 'MOTHERSHIP_API',
            'AMS Group' => 'AMS_GRP',
            'Daiichi Freight System Inc' => 'DAIICHI',
            'hk_rpx' => 'HK_RPX',
            'Posti API' => 'POSTI_API',
            'HFD' => 'HFD',
            'ATS Healthcare' => 'ATSHEALTHCARE',
            'DHL France (www.dhl.com' => 'DHL_FR',
            'Hero Express' => 'HEROEXPRESS',
            'hermesworld_uk' => 'HERMESWORLD_UK',
            'PARCLL' => 'PARCLL',
            'CEVA LOGISTICS' => 'CEVA',
            'Hermes UK' => 'HERMES_UK_SFTP',
            'Falcon Express' => 'FXTRAN',
            'HSM Global' => 'HSM_GLOBAL',
            'fastway_au' => 'FASTWAY_AU',
            'HanJin' => 'HANJIN',
            'Poste Italiane Paccocelere' => 'POSTE_ITALIANE_PACCOCELERE',
            'Luwjistik' => 'LUWJISTIK',
            'HomeRunner' => 'HOMERUNNER',
            'Groupe Mazet' => 'MAZET',
            'JD Worldwide' => 'JD_WORLDWIDE',
            'Optima Courier' => 'OPTIMACOURIER',
            'Gojek' => 'GOJEK',
            'Go Rush' => 'GORUSH',
            'SRT Transport' => 'SRT_TRANSPORT',
            'JNE (API' => 'JNE_API',
            'gls_italy_ftp' => 'GLS_ITALY_FTP',
            'Daeshin' => 'DAESHIN',
            'OSM Worldwide' => 'OSM_WORLDWIDE_SFTP',
            'GLS_FR' => 'GLS_FR',
            'dpd_uk' => 'DPD_UK',
            'GLS_DE' => 'GLS_DE',
            'AIRSPEED' => 'AIRSPEED',
            'Gati-KWE' => 'GATI_KWE_API',
            'COURIER POST' => 'COURIER_POST',
            'GLS Spain' => 'GLS_SPAIN_API',
            'Glovo' => 'GLOVO',
            'SHIPA' => 'SHIPA',
            'FASTWAY_UK' => 'FASTWAY_UK',
            'Global Post' => 'GOGLOBALPOST',
            'Shypmax' => 'SHYPLITE',
            'GIO Express Inc' => 'GIO_ECOURIER',
            'startrack_express' => 'STARTRACK_EXPRESS',
            'Papa' => 'PAPA_WEBHOOK',
            'Plycon Transportation Group' => 'PLYCONGROUP',
            'Giao hàng nhanh' => 'GIAO_HANG',
            'EFS (E-commerce Fulfillment Service' => 'EFS',
            'DHL eCommerce Greater China' => 'DHL_ECOMMERCE_GC',
            'Georgian Post' => 'GPOST',
            'GEODIS - Distribution & Express' => 'GEODIS_API',
            'SHIPXPRESS' => 'SHIPXPRES',
            'Fetchr' => 'FETCHR',
            'Mobi Logistica' => 'MOBI_BR',
            'Coordinadora' => 'COORDINADORA_API',
            'GEODIS' => 'GEODIS',
            'Gebr��der Weiss' => 'GW_WORLD',
            'Sequoialog' => 'NOWLOG_API',
            'INTEX Paketdienst GmbH' => 'INTEX_DE',
            'YYEXPRESS' => 'YYEXPRESS',
            'Total Express' => 'TOTAL_EXPRESS_API',
            'IB Venture' => 'IBVENTURE_WEBHOOK',
            'G.I.G' => 'GWLOGIS_API',
            'Dialogo Logistica' => 'DIALOGO_LOGISTICA',
            'fr_mondial' => 'FR_MONDIAL',
            'DPD Austria' => 'DPD_AT_SFTP',
            'fr_colissimo' => 'FR_COLISSIMO',
            'OM LOGISTICS LTD' => 'OMLOGISTICS_API',
            'Deliver-iT' => 'DELIVER_IT',
            'Hunter Express' => 'HUNTER_EXPRESS_SFTP',
            'Forward Air' => 'FORWARDAIR',
            'uParcel' => 'UPARCEL',
            'P2P TrakPak' => 'P2P_TRC',
            'eCoutier' => 'ECOUTIER',
            'GLS_ES' => 'GLS_ES',
            'Anteraja' => 'ANTERAJA',
            'DHL supply chain India' => 'DHL_SUPPLYCHAIN_IN',
            'FitzMark' => 'FITZMARK_API',
            'BERT' => 'BERT',
            'International Seur API' => 'INTERNATIONAL_SEUR_API',
            'first_logisitcs' => 'FIRST_LOGISITCS',
            'MNX' => 'MNX',
            'First Logistics' => 'FIRST_LOGISTICS_API',
            'India Post International' => 'INDIA_POST_INT',
            'fercam_it' => 'FERCAM_IT',
            'PANDU' => 'PANDU',
            'Axlehire' => 'AXLEHIRE_FTP',
            'Newgistics API' => 'NEWGISTICSAPI',
            'Link Bridge(BeiJing)international logistics co' => 'LINKBRIDGE',
            'FedEx��' => 'FEDEX_API',
            'Faxe Cargo' => 'FAXECARGO',
            'Royal Mail' => 'ROYAL_MAIL_FTP',
            'FASTWAY_US' => 'FASTWAY_US',
            'amazon_uk_api' => 'AMAZON_UK_API',
            'FAN COURIER EXPRESS' => 'FAN',
            'elta_gr' => 'ELTA_GR',
            'COURIERPLUS' => 'COURIERPLUS',
            'NEW ZEALAND COURIERS' => 'NEWZEALAND_COURIERS',
            'dhl_it' => 'DHL_IT',
            'fairsenden' => 'FAIRSENDEN_API',
            'dhl_global_mail' => 'DHL_GLOBAL_MAIL',
            'dhlparcel_uk' => 'DHLPARCEL_UK',
            'CBL Logistica (API' => 'CBL_LOGISTICA_API',
            'EWE Global Express' => 'EWE',
            'Rixon Logistics' => 'RIXONHK_API',
            'Patheon Logistics' => 'PATHEON',
            'DPEX (www.dpex.com' => 'DPEX',
            'Wish' => 'WISH_EMAIL_PUSH',
            'EVRi' => 'MYHERMES_UK_API',
            'TH_CJ' => 'TH_CJ',
            'Professional Parcel Logistics' => 'PPL',
            'DSV courier' => 'DSV',
            'eTotal Solution Limited' => 'ETOTAL',
            'Stat Overnight' => 'STATOVERNIGHT',
            'Expeditors' => 'EXPEDITORS',
            'ENSENDA' => 'ENSENDA',
            'Airterra' => 'AIRTERRA',
            'ecourier' => 'ECOURIER',
            'ECMS International Logistics Co' => 'ECMS',
            'Fastbox' => 'FASTBOX',
            'ECexpress' => 'ECEXPRESS',
            'Passport Shipping' => 'PASSPORTSHIPPING',
            'TNT_JP' => 'TNT_JP',
            'Tamer Logistics' => 'TAMERGROUP_WEBHOOK',
            'JD Logistics' => 'JD_EXPRESS',
            'DX Freight' => 'DX_FREIGHT',
            'Czech Post' => 'CESKAPOSTA_API',
            'ClickLink' => 'CLICKLINK_SFTP',
            'ems_cn' => 'EMS_CN',
            'ADS Express' => 'ADS',
            'BioCair' => 'BIOCAIR_FTP',
            'CEVA Package' => 'CEVA_TRACKING',
            'EC_CN' => 'EC_CN',
            'East West Courier Pte Ltd' => 'EASTWESTCOURIER_FTP',
            'DPEX' => 'CN_DPEX',
            'Fast Despatch Logistics Limited' => 'FASTDESPATCH',
            'dpd_fr_reference' => 'DPD_FR_REFERENCE',
            'FlipXpress' => 'FLIPXP',
            'Flight Logistics Group' => 'FLIGHTLG',
            'dpd_de' => 'DPD_DE',
            'TYP' => 'TYP',
            'CJ Logistics International' => 'CJ_LOGISTICS',
            'Bpost (www.bpost.be' => 'BE_BPOST',
            'DPD UK' => 'DPD_UK_SFTP',
            'DPD Slovakia' => 'DPD_SK_SFTP',
            'Hellmann Worldwide Logistics' => 'HELLMANN',
            'Copa Airlines Courier' => 'COPA_COURIER',
            'DPD Netherlands' => 'DPD_NL',
            'GLS' => 'GLS',
            'DHL Spain Domestic' => 'DHL_ES_SFTP',
            'DPD' => 'DPD',
            'Teleport' => 'TELEPORT_WEBHOOK',
            'DX (B2B' => 'DX_B2B_CONNUM',
            'us_apc' => 'US_APC',
            'taqbin_sg' => 'TAQBIN_SG',
            'iDexpress Indonesia' => 'IDEXPRESS_ID',
            'Keuhne + Nagel Global' => 'KNG',
            'jetship_my' => 'JETSHIP_MY',
            'Instabox' => 'INSTABOX_WEBHOOK',
            'DOTZOT' => 'DOTZOT',
            'Direx' => 'DIREX',
            'Spanish Seur' => 'SPANISH_SEUR_FTP',
            'DPD Switzerland' => 'DPD_CH_SFTP',
            'India Post Domestic' => 'INDIA_POST',
            'DNJ Express' => 'DNJ_EXPRESS',
            'LBC EXPRESS INC' => 'LBCEXPRESS_API',
            'C.H. Robinson Worldwide' => 'CHROBINSON',
            'DMF' => 'DMFGROUP',
            'SENHONG INTERNATIONAL LOGISTICS' => 'SHOWL',
            'Exelot Ltd' => 'EXELOT_FTP',
            'Yusen Logistics' => 'YUSEN_SFTP',
            'dhl_at' => 'DHL_AT',
            'DKSH' => 'DKSH',
            'GLOBEGISTICS' => 'GLOBEGISTICS',
            'Livrapide' => 'LIVRAPIDE',
            'StarTrack' => 'STAR_TRACK_WEBHOOK',
            'Kronos Express' => 'KRONOS',
            'dhl_supply_chain_au' => 'DHL_SUPPLY_CHAIN_AU',
            'LOGISTICSWORLDWIDE MY' => 'LOGISTICSWORLDWIDE_MY',
            'speedex' => 'SPEEDEX',
            'HUBBED' => 'HUBBED',
            'Go People' => 'GOPEOPLE',
            'DHL Supply Chain Indonesia' => 'DHL_SUPPLYCHAIN_ID',
            'dhl Singapore' => 'DHL_SG',
            'DHL Japan' => 'DHL_JP',
            'gls_spain' => 'GLS_SPAIN',
            'Testing Courier' => 'TESTING_COURIER',
            'SMG Direct' => 'SMG_EXPRESS',
            'DHL International' => 'IT_DHL_ECOMMERCE',
            'Barq' => 'BARQEXP',
            'Capital Transport' => 'CAPITAL',
            'J&T Express Philippines' => 'JTEXPRESS_PH',
            'ALLJOY SUPPLY CHAIN' => 'ALLJOY',
            'Bollore Logistics' => 'BOLLORE_LOGISTICS',
            'Flash Express' => 'FLASHEXPRESS_WEBHOOK',
            'DHL Global Forwarding API' => 'DHL_GLOBAL_FORWARDING_API',
            'dhl Global' => 'DHL',
            'ONTRAC' => 'ONTRAC',
            'Northline' => 'NORTHLINE',
            'GREYHOUND' => 'GREYHOUND',
            'A2B Express Logistics' => 'A2B_BA',
            'nacex_spain_reference' => 'NACEX_SPAIN_REFERENCE',
            'Kiala' => 'BE_KIALA',
            'EZship' => 'EZSHIP',
            'DPD delistrack' => 'DPD_DELISTRACK',
            'DHL Freight' => 'DHL_FREIGHT',
            'Deliverr' => 'DELIVERR_SFTP',
            'DHL Express' => 'DHL_SFTP',
            'DHL eCommerce Solutions' => 'DHL_GLOBAL_MAIL_API',
            'D Express' => 'DEXPRESS_WEBHOOK',
            'DHL' => 'DHL_API',
            'eurodis' => 'EURODIS',
            'SMARTCAT' => 'SMARTCAT',
            'Dependable Supply Chain Services' => 'GODEPENDABLE',
            'OrangeDS (Orange Distribution Solutions Inc' => 'ORANGE_DS',
            'dhl_pieceid' => 'DHL_PIECEID',
            'DAO365' => 'DAO365',
            'delivere' => 'DELIVERE',
            'STO Express' => 'CN_STO',
            'Chazki' => 'CHAZKI',
            'DHL GLOBAL FORWARDING PANAM��' => 'DHL_PA_API',
            'DB Schenker' => 'DBSCHENKER_API',
            'delcart_in' => 'DELCART_IN',
            'yodel' => 'YODEL',
            'Tusk Logistics' => 'TUSKLOGISTICS',
            'Day & Ross' => 'DAYROSS',
            'Eco Freight' => 'ECOFREIGHT',
            'DELTEC DE' => 'DELTEC_DE',
            'Metropolitan Warehouse & Delivery' => 'MWD_API',
            'DHL (Reference number' => 'DHL_REFERENCE_API',
            'Elite Express' => 'ELITE_CO',
            'Europacket' => 'EUROPAKET_API',
            'MUDITA' => 'MUDITA',
            'Hermes Germany' => 'HERMES_DE_FTP',
            'KedaEX' => 'KEDAEX',
            'Crossflight Limited' => 'CROSSFLIGHT',
            'Dynamic Logistics' => 'DYNALOGIC',
            'LOGISTICSWORLDWIDE KR' => 'LOGISTICSWORLDWIDE_KR',
            'asendia_de' => 'ASENDIA_DE',
            'Mensajeros Urbanos' => 'MENSAJEROSURBANOS_API',
            'DD Express Courier' => 'DDEXPRESS',
            'CryoPDP' => 'CRYOPDP_FTP',
            'Thunder Express Australia' => 'THUNDEREXPRESS',
            'fastway_za' => 'FASTWAY_ZA',
            'IML courier' => 'IML',
            'Carry-Flap Co' => 'CARRY_FLAP',
            'DACHSER' => 'DACHSER_WEB',
            'AIT' => 'AITWORLDWIDE_SFTP',
            'Mhi' => 'MHI',
            'Tipsa API' => 'TIPSA_API',
            'ComOne Express' => 'COM1EXPRESS',
            'Fastship Express' => 'FASTSHIP',
            'orangeconnex' => 'ORANGECONNEX',
            'WOO YOUNG LOGISTICS CO., LTD' => 'WOOYOUNG_LOGISTICS_SFTP',
            'Correos Express (API' => 'CORREOSEXPRESS_API',
            'Sending Transporte Urgente y Comunicacion' => 'SENDING',
            'DX' => 'DX',
            'DE DHL' => 'DE_DHL',
            'SHENZHEN HOTSIN CARGO INTL FORWARDING CO., LTD' => 'HOTSIN_CARGO',
            'AxleHire' => 'AXLEHIRE',
            'CANPAR' => 'CANPAR',
            'CJ GLS' => 'CJ_GLS',
            'Cago' => 'CAGO',
            'DB Schenker B2B' => 'DBSCHENKER_B2B',
            'Posta Plus' => 'POSTAPLUS',
            'Daylight Transport' => 'DYLT',
            'Chienventure' => 'CHIENVENTURE_WEBHOOK',
            'Iceland Post' => 'POSTUR_IS',
            'FRONTdoor Collective' => 'FRONTDOORCORP',
            'DSV Futurewave' => 'DSV_REFERENCE',
            'watkins_shepard' => 'WATKINS_SHEPARD',
            'Mondial Relay France' => 'MONDIALRELAY_FR',
            'Yamato Singapore' => 'TAQBIN_SG_API',
            'M&X cargo' => 'MX_CARGO',
            'EMS' => 'EMS',
            'FOUR PX EXPRESS' => 'FOUR_PX_EXPRESS',
            'Burd Delivery' => 'BURD',
            'InPost' => 'INPOST_UK',
            'Courant Plus' => 'COURANT_PLUS_API',
            'Aras Cargo' => 'ARASKARGO',
            'Speedy' => 'SPEEDY',
            'BUFFALO' => 'BUFFALO',
            'FLYTEXPRESS' => 'FLYTEXPRESS',
            'Packeta' => 'PACKETA',
            'BRT Bartolini API' => 'BRT_IT_API',
            'TNT_DE' => 'TNT_DE',
            'Parcel Right' => 'PARCELRIGHT',
            'Chile Express' => 'CHILEXPRESS',
            'FUJIE EXPRESS' => 'FUJEXP',
            'World Courier' => 'WORLDCOURIER',
            'Concise' => 'CONCISE_API',
            'Belpost' => 'BLR_BELPOST',
            'Bpost international' => 'BPOST_INT',
            'cj_philippines' => 'CJ_PHILIPPINES',
            'Bluedart' => 'BLUEDART_API',
            'Servientrega' => 'SERVIENTREGA',
            'ACOMMERCE' => 'ACOMMERCE',
            'UPS Reference' => 'UPS_REFERENCE',
            'BDMnet' => 'BDMNET',
            'Agediss' => 'AGEDISS_SFTP',
            'Magyar Posta' => 'MAGYAR_POSTA_API',
            'Allied Express (FTP' => 'ALLIED_EXPRESS_FTP',
            'Nippon Express' => 'NIPPON_EXPRESS',
            'U-ENVIOS' => 'U_ENVIOS',
            'DHL Active Tracing' => 'DHL_ACTIVE_TRACING',
            'Spectran' => 'SPECTRAN',
            'qualitypost' => 'QUALITYPOST',
            'BJS Distribution, Storage & Couriers - FTP' => 'BJSHOMEDELIVERY_FTP',
            'ECARGO' => 'ECARGO',
            'FedEx® Freight' => 'FEDEX_FR',
            'Bomi Group' => 'BOMI',
            'NimbusPost' => 'NIMBUSPOST',
            'GO Logistics & Storage' => 'GOLS',
            'CN Logistics' => 'CN_LOGISTICS',
            '99minutos' => '99MINUTOS',
            'Kiit��j��t' => 'LOGISYSTEMS_SFTP',
            'Javit' => 'JAVIT',
            'Big Smart' => 'BIGSMART',
            'fasttrack' => 'FASTTRACK',
            'bel_belgium_post' => 'BEL_BELGIUM_POST',
            'Direct Freight Express' => 'DIRECTFREIGHT_AU_REF',
            'deutsche_de' => 'DEUTSCHE_DE',
            'LCT do Brasil' => 'LCTBR_API',
            'HR Parcel' => 'HERMES_IT',
            'Deliver Your Parcel' => 'DELIVERYOURPARCEL_ZA',
            'Australia Post' => 'AUSTRALIA_POST_API',
            'Parcel To Post' => 'PARCEL_2_POST',
            'Bpost API' => 'BPOST_API',
            'TRANSMISSION' => 'TRANSMISSION',
            'Spreetail' => 'SPREETAIL_API',
            'BJS Distribution courier' => 'BJSHOMEDELIVERY',
            'Eurodifarm' => 'EDF_FTP',
            'Ohi' => 'OHI_WEBHOOK',
            'SPRINT PACK' => 'SPRINT_PACK',
            'Komon Express' => 'KOMON_EXPRESS',
            'ids_logistics' => 'IDS_LOGISTICS',
            'DHL Global Forwarding Guatemala' => 'DHL_GT_API',
            'ACI Logistix' => 'ACILOGISTIX',
            'COLLECTPLUS' => 'COLLECTPLUS',
            'Expeditors API Reference' => 'EXPEDITORS_API_REF',
            'Aramex' => 'ARAMEX_API',
            'Swiship IN' => 'AMAZON_FBA_SWISHIP_IN',
            'Shopee Xpress' => 'SPX_TH',
            'Celeritas Transporte' => 'CELERITAS',
            'Activos24' => 'ACTIVOS24_API',
            'J&T Express Singapore' => 'JTEXPRESS_SG_API',
            'Andreani' => 'ANDREANI_API',
            'Danniao' => 'DANNIAO',
            'Emirates Post' => 'ARE_EMIRATES_POST',
            'InTime' => 'INTIME_FTP',
            'Argents Express Group' => 'ARGENTS_WEBHOOK',
            'Au Express' => 'AUEXPRESS',
            'DB Schenker Iceland' => 'DBSCHENKER_ICELAND',
            'Amazon' => 'AMAZON_EMAIL_PUSH',
            'joyingbox' => 'JOYINGBOX',
            'City Express' => 'CITY56_WEBHOOK',
            'DHL Parcel NL' => 'DHL_PARCEL_NL',
            'BLUEDART' => 'BLUEDART',
            'Inntralog GmbH' => 'INNTRALOG_SFTP',
            'Vietnam Post' => 'VNPOST_API',
            'AEROFLASH' => 'AEROFLASH',
            'PIL Logistics (China) Co' => 'PIL_LOGISTICS',
            'AIR 21' => 'AIR_21',
            'pickupp_vnm' => 'PICKUPP_VNM',
            'Best Transport' => 'BESTTRANSPORT_SFTP',
            'DemandShip' => 'DEMANDSHIP',
            'correos Express (www.correos.es' => 'CORREOS_ES',
            'Ozeparts Shipping' => 'OZEPARTS_SHIPPING',
            'AB Custom Group' => 'ABCUSTOM_SFTP',
            'Amazon order' => 'AMAZON_ORDER',
        ],
        'NLD' => [
            'Paper Express' => 'PAPER_EXPRESS',
            'Happy 2ThePoint' => 'HAPPY2POINT',
            'GLS Netherland' => 'NLD_GLS',
            'Trunkrs courier' => 'TRUNKRS_WEBHOOK',
            'DHL Netherland' => 'NLD_DHL',
            'Fiege Netherlands' => 'FIEGE_NL',
            'PostNL International 3S' => 'POSTNL_INTL_3S',
            'Brouwer Transport en Logistiek' => 'BROUWER_TRANSPORT',
        ],
        'KHM' => [
            'Cambodia Post' => 'KHM_CAMBODIA_POST',
            'Roadbull Logistics' => 'ROADRUNNER_FREIGHT',
            'AFL LOGISTICS' => 'AFLLOG_FTP',
        ],
        'JPN' => [
            'Seino' => 'SEINO',
            'MailPlus (Japan' => 'MAILPLUS_JPN',
            'MailPlus' => 'MAIL_PLUS',
            'KWE Global' => 'KWE_GLOBAL',
            'Japan Post' => 'JPN_JAPAN_POST',
            'eFEx (E-Commerce Fulfillment & Express' => 'EFEX',
        ],
        'FRA' => [
            'VIR Transport' => 'VIRTRANSPORT',
            'TNT France' => 'TNT_FR',
            'Heppner France' => 'HEPPNER_FR',
            'DPD France (formerly exapaq' => 'FR_EXAPAQ',
            'DPD France' => 'DPD_FR',
            'Cubyn' => 'CUBYN',
            'Colis Privé' => 'COLIS_PRIVE',
            'La Poste' => 'LA_POSTE_SUIVI',
            'Geodis E-space' => 'GEODIS_ESPACE',
            'Colissimo' => 'FR_COLIS',
            'Chronopost france (www.chronopost.fr' => 'CHRONOPOST_FR',
        ],
        'SGP' => [
            'Zyllem' => 'ZYLLEM',
            'Urbanfox' => 'COUREX',
            'Fonsen Logistics' => 'FONSEN',
            'Jayon Express (JEX' => 'IND_JAYONEXPRESS',
            'TCK Express' => 'TCK_EXPRESS',
            'Red Carpet Logistics' => 'ROADBULL',
            'Singapore Speedpost' => 'SG_SPEEDPOST',
            'RaidereX' => 'RAIDEREX',
            'PICK UPP (Singapore' => 'PICKUPP_SGP',
            'Parcel Post Singapore' => 'PARCELPOST_SG',
            'RZY Express' => 'RZYEXPRESS',
            'Nhans Solutions' => 'NHANS_SOLUTIONS',
            'Qxpress' => 'SG_QXPRESS',
            'WMG Delivery' => 'WMG',
            'Park N Parcel' => 'PARKNPARCEL',
            'Legion Express' => 'LEGION_EXPRESS',
            'KGM Hub' => 'KGMHUB',
            'J&T Express Singapore' => 'SIMPLYPOST',
            'Jet-Ship Worldwide' => 'JET_SHIP',
            'Grab courier' => 'GRAB_WEBHOOK',
            'Ninja van Singapore' => 'NINJAVAN_SG',
            'Singapore Post' => 'SG_SG_POST',
            'Janio Asia' => 'JANIO',
            'Detrack' => 'SG_DETRACK',
            'Cloudwish Asia' => 'CLOUDWISH_ASIA',
        ],
        'KWT' => [
            'Posta Plus' => 'POSTA_PLUS',
        ],
        'BEL' => [
            'Mikropakket Belgium' => 'MIKROPAKKET_BE',
            'Landmark Global' => 'LANDMARK_GLOBAL',
            'DHL Benelux' => 'BEL_DHL',
            'dhl benelux' => 'DHL_BENELUX',
            'Landmark Global Reference' => 'LANDMARK_GLOBAL_REFERENCE',
            'B2C courier Europe' => 'B_TWO_C_EUROPE',
        ],
        'HKG' => [
            'Zeek2Door' => 'ZEEK_2_DOOR',
            'Zeek courier' => 'SFPLUS_WEBHOOK',
            'RPX Online' => 'RPX',
            'Pickupp' => 'PICKUP',
            'Omni Parcel' => 'OMNIPARCEL',
            'Smooth Couriers' => 'SMOOTH',
            'CJ Logistics International(Hong Kong' => 'CJ_HK_INTERNATIONAL',
            'LHT Express' => 'LHT_EXPRESS',
            'DHL Global Mail Asia (www.dhl.com' => 'DHL_GLOBAL_MAIL_ASIA',
            'JS EXPRESS' => 'JS_EXPRESS',
            'Hongkong Post (www.hongkongpost.hk' => 'HK_POST',
            'Globavend' => 'GLOBAVEND',
            'CL E-Logistics Solutions Limited' => 'CLE_LOGISTICS',
            'DealerSend' => 'DEALERSEND',
            'DTDC express' => 'DTDC_EXPRESS',
            'DHL HonKong' => 'DHL_HK',
            'Logistic Worldwide Express (LWE Honkong' => 'LOGISTICSWORLDWIDE_HK',
            'Kerry eCommerce' => 'KERRY_ECOMMERCE',
            'Quantium' => 'QUANTIUM',
            'DPD HongKong' => 'DPD_HK',
            'DHL eCommerce Asia (API' => 'DHL_ECOMERCE_ASA',
            'Janco Ecommerce' => 'JANCO',
            'STEP FORWARD FREIGHT SERVICE CO LTD' => 'STEPFORWARDFS',
            'Continental' => 'CONTINENTAL',
            'Ship It Asia' => 'SHIP_IT_ASIA',
            'PAL Express Limited' => 'PALEXPRESS',
            'OkayParcel' => 'OKAYPARCEL',
            'Mainway' => 'MAINWAY',
            'Cosmetics Now' => 'COSTMETICSNOW',
            'SEKO Logistics' => 'SEKOLOGISTICS',
            'Morning Express' => 'MORNING_EXPRESS',
            'KEC courier' => 'KEC',
            'CFL Logistics' => 'CFL_LOGISTICS',
        ],
        'ARG' => [
            'Grupo logistico Andreani' => 'ANDREANI',
            'OCA Argentina' => 'ARG_OCA',
            'Fasttrack' => 'FASTRACK',
        ],
        'AUT' => [
            'Austrian Post (Registered' => 'AU_AUSTRIAN_POST',
            'austrian post' => 'AUSTRIAN_POST_EXPRESS',
        ],
    ];

    /**
     * @var array
     */
    private $carriers;

    public function __construct(
        TranslatorInterface $translator,
        array $locales,
        array $carriers
    ) {
        parent::__construct($translator, $locales);

        $this->carriers = $carriers;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('carrierId', ChoiceType::class, [
                'choices' => $this->carriers,
                'label' => $this->trans('Carrier name', 'Modules.Paypaltracking.Admin'),
                'constraints' => [
                    new NotBlank([
                        'message' => $this->trans(
                            'This field cannot be empty.',
                            'Admin.Notifications.Error'
                        ),
                    ]),
                ],
            ])
            ->add('paypalCarrierEnum', ChoiceType::class, [
                'choices' => self::PAYPAL_CARRIERS,
                'label' => $this->trans('Paypal carrier enum', 'Modules.Paypaltracking.Admin'),
                'constraints' => [
                    new NotBlank([
                        'message' => $this->trans(
                            'This field cannot be empty.',
                            'Admin.Notifications.Error'
                        ),
                    ]),
                ],
            ])
            ->add('countryId', CountryChoiceType::class, [
                'label' => $this->trans('Country', 'Admin.Global'),
                'constraints' => [
                    new NotBlank([
                        'message' => $this->trans(
                            'This field cannot be empty.',
                            'Admin.Notifications.Error'
                        ),
                    ]),
                ],
            ])
            ->add('worldwide', SwitchType::class, [
                'label' => $this->getTranslator()->trans('Is worldwide?', [], 'Modules.Paypaltracking.Admin'),
                'required' => true,
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                'translation_domain' => 'Modules.Paypaltracking.Admin',
            ]);
    }
}
